### ISSUE TITLE
"Stars Background" Not Showing Up

### ISSUE THREAD

**Issue by CommanderZel** [edmundojr/tumblr-darkhorse#1]
Hi, I just installed the Dark Side theme, and it's working great except for the fact that the stars aren't appearing. Is there any way to fix that?
Thank you!

**Comment by manfromanotherland** [comment]
Hi, thanks for opening an issue. What browser are you using? The stars background should be the same as seen on the [demo theme page](https://darkside-theme.tumblr.com/).

**Comment by Yomi4** [comment]
Hi, same problem here. I'm using chrome, how can i fix it? Ty. 
(Ps. in the same browser the demo theme page is working great)

**Comment by manfromanotherland** [comment]
@Yomi4 have you enabled the starts background on the customizations panel?
